### ISSUE TITLE
Spacing issues after input

### ISSUE THREAD

**Issue by madcampos** [Jaykul/PowerLine#13]
On Windows 10 (Build 15063, PS version 5.1.15063.0) there is some spacing issues, when the line is created there is a space before each part, and after typing anything the spaces go to the front of the line. Here are some screenshots.

Spaces before sections:
![2017-04-10 4](https://cloud.githubusercontent.com/assets/609904/24877306/c3273140-1dfc-11e7-9319-eb967ad052b5.png)

Spaces after input:
![2017-04-10 3](https://cloud.githubusercontent.com/assets/609904/24877340/dcd1554e-1dfc-11e7-8154-469fc886ffcf.png)

The number of spaces seems to be mantained.
![2017-04-10 5](https://cloud.githubusercontent.com/assets/609904/24877408/2556f256-1dfd-11e7-8ce3-27a90ad9b4ef.png)

**Comment by Jaykul** [comment]
Yep. I have noticed this as well. I'm not sure what is causing it, but will look into it after I finish merging [Pansies](/PoshCode/Pansies/)

**Comment by powercode** [comment]
I don't think it is you @Jaykul, I think it is a bug in the Console.
Seems to render a space after multibyte chars.

An interesting test is to do the following:

# change font to Consolas
cls
# watch the prompt render with missing glyphs
# change font to a Powerline font
# watch the prompt render correctly
<enter>
# watch prompt render messed up again

**Comment by Jaykul** [comment]
So I guess I can close this now?
