### ISSUE TITLE
Question Marks in place of characters in ConEmu

### ISSUE THREAD

**Issue by mitchellmaler** [Jaykul/PowerLine#19]
Hello, 

I just setup PowerLine in my console with the example setup in the readme. Currently it seems to be working correctly but I am getting question marks in the console instead of characters. Seems like an ASCII issue and was wondering if I just missed something to get them to show. 

![image](https://user-images.githubusercontent.com/4107699/27294737-3f43424a-54e0-11e7-8586-14ed3ec6e73d.png)

**Comment by weloytty** [comment]
What font are you using?  You have to use the powerline  fonts, I got them from https://github.com/PowerLine/fonts

**Comment by mitchellmaler** [comment]
Ah that would do it. Missed that part. Thanks!
