### ISSUE TITLE
PowerLine seems to install correctly, but fails when enabled in profile.ps1

### ISSUE THREAD

**Issue by erwinwolff** [Jaykul/PowerLine#21]
The installation of PowerLine seemed to succeed inside powershell, but when I added

```
#requires -module PowerLine
using module PowerLine

$PowerLinePrompt = @(
        @{ bg = "Cyan";     fg = "White"; text = { $MyInvocation.HistoryId } }
        @{ bg = "DarkBlue"; fg = "White"; text = { $pwd } }
    )

Set-PowerLinePrompt -PowerLineFont
```

To my Microsoft.PowerShell_profile.ps1 the startup of the Powershell window ended in this:

```
The property 'UseAnsiEscapes' cannot be found on this object. Verify that the property exists and can be set.
t C:\Program Files\WindowsPowerShell\Modules\PowerLine\2.3.1\PowerLine.psm1:420 char:5
     $global:PowerLinePrompt.UseAnsiEscapes = $UseAnsiEscapes
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
   + FullyQualifiedErrorId : PropertyAssignmentException

he property 'RestoreVirtualTerminal' cannot be found on this object. Verify that the property exists and can be set.
t C:\Program Files\WindowsPowerShell\Modules\PowerLine\2.3.1\PowerLine.psm1:421 char:5
     $global:PowerLinePrompt.RestoreVirtualTerminal = $RestoreVirtualT ...
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
   + FullyQualifiedErrorId : PropertyAssignmentException
```

Does anyone has some ideas on this?

**Comment by weloytty** [comment]
Take a  look at #16 

From what I can tell the next release is going to work differently, but hopefully this will get you by until then.  To get the code to work reliably (on Win7 and Win10, I've never tried it on a mac or linux), you have to open up PowerLine.psm1 from wherever you installed it and change all instances of [RgbColor] to [PoshCode.Pansies.RgbColor].  

On my machine, the file is at C:\Program Files\WindowsPowerShell\Modules\PowerLine\2.3.1, but it could be in your $PROFILE\Modules|\PowerLine

**Comment by erwinwolff** [comment]
Just look at that. It kind of works. But it is by no means a permanent solution.

**Comment by Jaykul** [comment]
I think your problem is that you're pre-creating the $PowerLinePrompt instead of passing the values to `Set-PowerLinePrompt` -- hopefully that'll be address by the new version (which, incidentally, doesn't leak $PowerLinePrompt outside the module, but instead uses a simple list of ScriptBlocks in $Prompt)
