### ISSUE TITLE
3.0 modules that update the prompt break the powerline prompt

### ISSUE THREAD

**Issue by weloytty** [Jaykul/PowerLine#22]
I understand what is happening here, but I don't really know why:

I set my powerline prompt as:
`    [System.Collections.Generic.List[ScriptBlock]]$Global:Prompt = @(
        { if ($Global:IsAdmin) {New-PromptText {"ADMIN"} -BackgroundColor DarkRed -ForegroundColor Yellow}else {"" }},
        {New-PromptText {$(Convert-Path -Path $(Get-Location))} -ForegroundColor Cyan  -BackgroundColor Magenta}
        )
`

   ` Set-PowerLinePrompt -Prompt $Global:Prompt -FullColor -PowerLineFont -Title { "{0} ({1})" -f (Convert-Path $pwd), $pwd.Provider.Name } #-Newline `

This works fine, UNTIL I load Zlocation, which plops "Update-ZLocation $pwd" at the top of the prompt function.

So after zLocation does its thing in the prompt, my prompt ends up as PS> (i.e. the default), and $error says:

`PS>$error                                                                                                        
The variable '$Script:PowerLineConfig' cannot be retrieved because it has not been set.                          
The variable '$Script:PowerLineConfig' cannot be retrieved because it has not been set.                          
At line:7 char:9  `                                                                                               
`+     if ($Script:PowerLineConfig.Title) {          `                                                             
`+         ~~~~~~~~~~~~~~~~~~~~~~~             `                                                                   
`    + CategoryInfo          : InvalidOperation: (Script:PowerLineConfig:String) [], RuntimeException    `         
`    + FullyQualifiedErrorId : VariableIsUndefined                   `                                             
                                                                                                                 
`PS>  `                                                                                                            

I don't understand why $Script:PowerLineConfig ends up null after zLocation, but if I add 
`$Script:PowerLineConfig = $(Get-Module PowerLine|Import-Configuration)`

right after `[bool]$Script:LastSuccess = $?` in prompt.ps1, all is well again (i.e. the configuration is reloaded and $Script.PowerLineConfig.Title doesnt raise an exception).

**Comment by weloytty** [comment]
I still don't know why this only appears until after another module modifies function:prompt, but the reason I get the error and thus the bare prompt is because I have `Set-StrictMode -Version Latest` at the top of my $PROFILE.  If I remove that, the errant behavior doesn't happen, without trying to reload the configuration.

**Comment by weloytty** [comment]
fixed in 71c0aa4c3eb82949b318728f5030bde46ed93e1c

**Comment by jasonmarcher** [comment]
FYI, this is likely because ZLocation is defining `prompt` by writing to the `function:` drive.  This defines it in the global scope which overrides PowerLine's copy.  From then on, `prompt` runs in global scope and no longer has access to private (`script` scope) variables in PowerLine.

**Comment by Jaykul** [comment]
The full fix is to re-run Powerline's `Set-PowerLinePrompt` and then add ZLocation's hook as a block:

```PowerShell
Set-PowerLinePrompt
Add-PowerLineBlock { Update-ZLocation $pwd }
```

Of course, the best thing would be for ZLocation itself to update the prompt function by appending to `$Prompt` instead of hacking your function...
