### ISSUE TITLE
Inconsistent color selection in 3.0

### ISSUE THREAD

**Issue by cdhunt** [Jaykul/PowerLine#23]
The prompt section colors change when using `-ErrorBackground`.

```
 "`t"
New-PromptText {Get-ElapsedHumanized}  -ErrorBackground DarkRed
 "`n"
New-PromptText {$SessionTitleName}  -ElevatedForegroundColor Yellow
 Get-SegmentedPath
 "`n"
 'PS ' + '>' * ($nestedPromptLevel + 1)
```

![hyper_2017-10-26_13-54-27](https://user-images.githubusercontent.com/114173/32068895-9232a0a6-ba55-11e7-8268-acc4f6f0e01c.png)

    Name      Version
    ----      -------
    PowerLine 3.0.3

    Name                           Value
    ----                           -----
    PSVersion                      5.1.15063.674
    PSEdition                      Desktop
    PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
    BuildVersion                   10.0.15063.674

**Comment by Jaykul** [comment]
Ah, yeah, so...

So there's a `Colors` array (see `$Prompt.Colors` and the `-Colors` switch 

Each output block _that does **not** already have a background color_ gets a color from the array.

If you specify an `-ErrorBackground` without specifying a `-Background` then that block "uses" a color from the colors array only when there's no error.

**Comment by cdhunt** [comment]
Got it.  Looking good now. 👍
