### ISSUE TITLE
How to 'reset' prompt variable

### ISSUE THREAD

**Issue by stefanstranger** [Jaykul/PowerLine#24]
After some tests I want to clean up my prompt how do I do that?

**Comment by stefanstranger** [comment]
Solved with rm $env:APPDATA\WindowsPowerShell\HuddledMasses.org\PowerLine\Configuration.psd1

**Comment by Jaykul** [comment]
I think my recommendation is:

```posh
Get-Module Powerline | Get-ConfigurationPath | Remove -Recurse
```

I keep thinking people will start learning the Configuration module, but it's not as popular as I'd hoped 😉
