### ISSUE TITLE
Module trying to overwrite 'Write-Host'

### ISSUE THREAD

**Issue by RobLMartin** [Jaykul/PowerLine#29]
This error after 'Install-Module PowerLine' and then agreeing to an 'Untrusted repository'.

PackageManagement\Install-Package : The following commands are already available on this system:'Write-Host'. This
module 'Pansies' may override the existing commands. If you still want to install this module 'Pansies', use
-AllowClobber parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Packag
   e], Exception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.
   PackageManagement.Cmdlets.InstallPackage

**Comment by pauby** [comment]
The Pansies module has a Write-Host function which obviously conflicts with the one on your system. Run `Install-Module PowerLine -AllowClobber` to install.

**Comment by Jaykul** [comment]
The warning you're getting is because the PANSIES module has an improved version of Write-Host (it supports full RGB colors and is _faster_). One of these days I'll probably "fix" that by changing the name of the PANSIES `Write-Host` command, but until then... it's harmless (and even beneficial) 🤪
