### ISSUE TITLE
I want to set the Host title to my own custom string

### ISSUE THREAD

**Issue by rkeithhill** [Jaykul/PowerLine#3]
Right now `PowerLineBlock.SetTitle` isn't flexible enough. Perhaps you could add property that takes a scriptblock that would get invoked to provide text to display in the Host's titlebar.

**Comment by Jaykul** [comment]
Yes! My intention was to do exactly that. I'm not sure why I did it as a switch, except that originally, there wasn't even a switch, because I was thinking that probably people would still use their own prompt functions, not mine...

**Comment by Jaykul** [comment]
Made it a scriptblock while I was breaking everything in v2.0.0
