### ISSUE TITLE
Error when invoking Set-PowerLinePrompt

### ISSUE THREAD

**Issue by TheWashiba** [Jaykul/PowerLine#30]
I'm getting an error when invoking `Set-PowerLinePrompt` in profile.ps1

Import-Metadata : At C:\Users\lukas\AppData\Roaming\powershell\HuddledMasses.org\PowerLine\Configuration.psd1:21 char:102
\+ ... .CurrentLocation '),(ScriptBlock ' '>' * ($nestedPromptLevel + 1) '))
\+                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Redirection is not allowed in restricted language mode or a Data section.
At C:\Program Files\WindowsPowerShell\Modules\Configuration\1.3.0\Configuration.psm1:417 char:21
\+ ...             Import-Metadata $EnterprisePath -ErrorAction Ignore -Orde ...
\+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (@{
  EscapeSequ... 'Gray'))
  }
}:ScriptBlock) [Import-Metadata], ParseException
    + FullyQualifiedErrorId : Metadata Error,Import-Metadata

My PowerShell:
> PSVersion                      5.1.17134.1
> PSEdition                      Desktop
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
> BuildVersion                   10.0.17134.1
> CLRVersion                     4.0.30319.42000
> WSManStackVersion              3.0
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1

I'm new to PowerShell, so it might be after all a problem on my side, just not sure what kind of.

**Comment by Thraka** [comment]
Doing some quick searching I found that you're locked down for some reason. This could be based on your OS perhaps (windows server?) or your IT department has locked down powershell.

Either way, you want to start investigating by searching for `pslanguagemode powershell`. Somewhere in that config area is your answer. I'm not familiar with this, so I can't really help you. I even found [this about IIS](https://devblog.rayonnant.net/2011/05/04/exchange-remote-powershell-pslanguagemode-to-fulllanguage/) though that may be too old to help. Unsure.

**Comment by TheWashiba** [comment]
I'm using Windows 10 Pro 1803, although it's licensed by university (Microsoft Imagine program), are you saying this could have an impact somehow? @Thraka 
I've also ran the "echo $Host.Runspace.LanguageMode", it showed FullLanguage mode was on.

**Comment by Thraka** [comment]
Unsure, I'm just letting you know what I found from doing some searches.

How did you install it? I used Get-Module I believe.

**Comment by TheWashiba** [comment]
I installed it thru `Install-Module` as suggested, I'm on `Powershell 5.1` version. @Thraka

**Comment by microhobby** [comment]
@TheWashiba how did you solve this issue, I am having the same behavior here.

**Comment by TheWashiba** [comment]
> @TheWashiba how did you solve this issue, I am having the same behavior here.

I don't remember, have switched to bash long time ago.

**Comment by TBBle** [comment]
I just bounced off this. The problem is that whatever is importing the psd1 file is seeing `>` and thinks it's a shell redirect. I changed it to ">" and it works correctly.
