### ISSUE TITLE
How do I uninstall this ?

### ISSUE THREAD

**Issue by sushruth** [Jaykul/PowerLine#34]
Can you please include instructions to uninstall and reset the prompt to what it was before?

**Comment by Jaykul** [comment]
All you have to do is not import the module. If you don't import the module, it doesn't change the prompt.

Obviously you can uninstall it. Use the same process as with any other module, just run: `Uninstall-Module PowerLine`, or if you installed it by hand, just delete the folder.

PowerLine doesn't make **any** changes to your profile or anything. There might be a config file (if you've exported it) but you can just leave it behind, or delete it _ahead of time_ by running: `Get-Module PowerLine | Get-ConfigurationPath | Remove-Item -Recurse -Confirm`
