### ISSUE TITLE
Conditional block colors

### ISSUE THREAD

**Issue by pf1gura** [Jaykul/PowerLine#47]
Is there a way to conditionally set BackgroundColor and ForegroundColor for blocks? I am trying to setup different colors based on git changes, same as Fish shell does it.
![image](https://user-images.githubusercontent.com/41795518/60207868-35945100-9857-11e9-9569-b9a337a1d4f9.png)

**Comment by Jaykul** [comment]
Yes. Use `New-PowerLineBlock` and set the `-BackgroundColor` conditionally in the script block, like:

```posh
Add-PowerLineBlock { 
    New-PowerLineBlock -Text "Hello" -BackgroundColor $(
        if( (Get-Date).Second % 2 ) { "Green" } else { "Orange" }
    )
} -Index 1
```
![image](https://user-images.githubusercontent.com/192942/67621874-134d1880-f7e2-11e9-9754-5a870d6ad22c.png)

**Comment by microhobby** [comment]
There is a way of use this `-BackgroundColor` on script blocks?
