### ISSUE TITLE
Can't install with Pansies 1.4.0-beta03

### ISSUE THREAD

**Issue by ato2** [Jaykul/PowerLine#55]
VERBOSE: For publisher validation, using the previously-installed module 'Pansies' with version '1.4.0' under 'C:\Program
Files\WindowsPowerShell\Modules\Pansies\1.4.0' with publisher name 'CN=Joel H. Bennett, O=Joel H. Bennett, L=West Henrietta, S=New York,
C=US' from root certificate authority 'CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US'. Is this module signed by
 Microsoft: 'False'.
PackageManagement\Install-Package : The version '1.2.1' of the module 'Pansies' being installed is not catalog signed. Ensure that the vers
ion '1.2.1' of the module 'Pansies' has the catalog file 'Pansies.cat' and signed with the same publisher 'CN=Joel H. Bennett, O=Joel H. Be
nnett, L=West Henrietta, S=New York, C=US' as the previously-installed module 'Pansies' with version '1.4.0' under the directory 'C:\Progra
m Files\WindowsPowerShell\Modules\Pansies\1.4.0'. If you still want to install or update, use -SkipPublisherCheck parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.2\PSModule.psm1:9683 char:34
+ ... talledPackages = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : ModuleIsNotCatalogSigned,Validate-ModuleAuthenticodeSignature,Microsoft.PowerShell.PackageManagement.Cmdlets
   .InstallPackage

**Comment by Jaykul** [comment]
Hah. This was obviously fixed a long time ago. PANSIES is on 2.1.0 previews now.
