### ISSUE TITLE
Support for no background colour

### ISSUE THREAD

**Issue by Riiskyy** [Jaykul/PowerLine#57]
Hi, I've recently managed to get this set up and I have been enjoying the customization features. However there is one issue I find with my specific set up.

I am using the new Windows Terminal and if I switch off 'useAcrylic' I can set the background colour of the my powerline to the colour of the terminal and it looks great. However I like to use Terminal with the acrylic setting enabled, however in this case I can now see the background colour:

![image](https://user-images.githubusercontent.com/30751766/73537454-6d342e80-4420-11ea-97b9-80f61ab80ad2.png)

I found that it is also not possible to remove the colour from the configuration.psd1 to leave only the text. Is this something that is possible to support?

**Comment by Jaykul** [comment]
I believe you can achieve this now with:

```PowerShell
[PoshCode.Pansies.Entities]::ExtendedCharacters["ColorSeparator"]=""
$Prompt.Colors = @($null) * $Prompt.Count
```

But this is (as always) not well documented.

**Comment by Riiskyy** [comment]
Thanks Jaykul that's done the trick. Although it has now opened up something else (again probable more related to my specific use of this module. But the text that goes on to a newline is i different colour to the rest of the prompt e.g.

![image](https://user-images.githubusercontent.com/30751766/126787182-d2627dbb-b38a-4b4b-b27b-5de8545f9f7f.png)

This is the current contents of `C:\Users\<Username>\AppData\Roaming\powershell\HuddledMasses.org\PowerLine\Configuration.psd1`

```
@{
  EscapeSequences    = @{
    Esc    = '['
    Store  = '[s'
    Recall = '[u'
    Clear  = '[0m'
  }
  ExtendedCharacters = @{
    ColorSeparator        = ' '
    ReverseColorSeparator = ' '
    Separator             = ' '
    ReverseSeparator      = '|'
    Branch                = ''
    Lock                  = ''
    Gear                  = '⛯'
    Power                 = '⚡'
  }
  PowerLineConfig    = @{
    Prompt                 = @(
      (ScriptBlock 'New-PromptText {"╭"} -ErrorForegroundColor Red; if(Write-VcsStatus) {New-PromptText {""} -ForegroundColor Green -ErrorForegroundColor Red}'),
      (ScriptBlock '$executionContext.SessionState.Path.CurrentLocation'),
      (ScriptBlock 'New-PromptText {"|"} -ErrorForegroundColor Red'),
      (ScriptBlock 'Get-Elapsed -Format "{0:mm\:ss\.f}"; if(Get-Elapsed){ New-PromptText {"|"} -ErrorForegroundColor Red}'),
      (ScriptBlock 'Get-Date -f "dd-MMM HH:mm UTCz"'),
      (ScriptBlock '"`n"'),
      (ScriptBlock 'if(-not (Write-VcsStatus)) {New-PromptText {"╰>"} -ErrorForegroundColor Red} else{New-PromptText {"╰"} -ErrorForegroundColor Red; Write-VcsStatus; New-PromptText {">"} -ErrorForegroundColor Red}')
    )
    DefaultAddIndex        = -1
    RestoreVirtualTerminal = $True
    Title                  = (ScriptBlock '"PowerShell"')
    FullColor              = $True
    Colors                 = @(@($null) * 4)
  }
}
```

**Comment by Jaykul** [comment]
I can't tell why the color changed there ... this seems to work for me:

```PowerShell
$CFG = @{
    Prompt                 = @(
      {New-PromptText {"╭"} -ErrorForegroundColor Red; if(Write-VcsStatus) {New-PromptText {""} -ForegroundColor Green -ErrorForegroundColor Red}}
      {$executionContext.SessionState.Path.CurrentLocation}
      { New-PromptText {"|"} -ErrorForegroundColor Red }
      { Get-Elapsed -Format "{0:mm\:ss\.f}"; if(Get-Elapsed){ New-PromptText {"|"} -ErrorForegroundColor Red} }
      { Get-Date -f "dd-MMM HH:mm UTCz" }
      {"`n"},
      {
      if(-not (Write-VcsStatus)) {
         New-PromptText {"╰>"} -ErrorForegroundColor Red
      } else { 
         New-PromptText {"╰"} -ErrorForegroundColor Red
         Write-VcsStatus; 
         New-PromptText {">"} -ErrorForegroundColor Red
      }
      }
    )
    RestoreVirtualTerminal = $True
    Title                  = {"PowerShell"}
    FullColor              = $True
    Colors                 = @(@($null) * 3)
}
Set-PowerLinePrompt @CFG
[PoshCode.Pansies.Entities]::ExtendedCharacters["ColorSeparator"]=""
```

![image](https://user-images.githubusercontent.com/192942/131230878-0b351b01-fd33-4399-8c12-31dfdbb0a729.png)

**Comment by Riiskyy** [comment]
Ok it must be something on my side then. I'll consider this closed, thank you
