### ISSUE TITLE
Needed to install prerelease Pansies

### ISSUE THREAD

**Issue by stej** [Jaykul/PowerLine#61]
Just wanted to try that module, so I went with

```
Install-Module PANSIES -AllowClobber
Install-Module PowerLine
Import-Module PowerLine
```

which gives me

```
WARNING: Exception in PowerLinePrompt
Unable to find type [PoshCode.Pansies.Console.WindowsHelper].
```

What solved this problem is installing latest beta version - 1.4.0-beta03

```
Install-Module Pansies -Scope Currentuser -AllowPrerelease -AllowClobber -Force
```

I would find it helpful to add that to doc or somehow clarify how to get it working with 1.3.0 (which is installed by default).

**Comment by nlinnett** [comment]
What version of powershell do I need for --AllowPrerelease? 5.1 gives an error on that parameter

**Comment by Jaykul** [comment]
It's a newer PowerShellGet that you need, @nlinnett

**Comment by Jaykul** [comment]
You should not need a pre-release PANSIES now, right?

**Comment by stej** [comment]
Now if I run the commands from documentation, it works well. Closing.
