### ISSUE TITLE
Error With New PowerShell 7.1 preview 2 - Get-Date Usage Needs Full Parameter Name

### ISSUE THREAD

**Issue by BouwenMA** [Jaykul/PowerLine#62]
The new [PowerShell 7.1 preview 2](https://github.com/PowerShell/PowerShell/releases/tag/v7.1.0-preview.2) adds a new parameter to "Get-Date" called "-FromUnixTime":

> Add -FromUnixTime to Get-Date to allow Unix time input (#12179) (Thanks @jackdcasey!)

The following error is now produced upon importing the module:

> WARNING: Exception thrown from prompt block. Check $PromptErrors. To suppress this message, Set-PowerLine -HideError
> Parameter cannot be processed because the parameter name 'f' is ambiguous. Possible matches include: -Format -FromUnixTime.

This appears due to PowerLine using 'Get-Date -f "T"'.  It would appear that PowerLine is using it as an abbreviated form of the "-Format" _Parameter_ of "Get-Date", rather than the "-f" _Format Operator_.  PowerShell also seems to parse it that way, as using the "-f" Format Operator yields both date and time in PSH v5.1, 7.0, and 7.1p2:

> PS B:\PSH7.1> (Get-Date) -F "T"
> 04/25/2020 16:16:14
> PS B:\PSH7.1> Get-Date -Format "T"
> 16:16:59

It looks like these source scripts need changes to replace the "-f" with "-Format":

> Source\Examples\Sample.ps1:    { Get-Date -f "T" }
> Source\Examples\SampleForConsolas.ps1:    { Get-Date -f "T" }
> Source\Public\Set-PowerLinePrompt.ps1:                { Get-Date -f "T" }

Please let me know if you have any questions.  Thank you.

**Comment by jackdcasey** [comment]
Good catch! 

I can get a PR opened to address this, as I feel somewhat responsible 😁

**Comment by BouwenMA** [comment]
> Good catch!
> 
> I can get a PR opened to address this, as I feel somewhat responsible 😁

Thank you @jackdcasey !  You're not responsible, but I still appreciate the help!  First by submitting the PR...  Second, by seeing the way you are doing it here I'm also learning how by example to do similar myself in the future.  I appreciate it.
